services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Событие запуска отложенных событий по OnEpilog.
  framework_extension.on_epilog_flush_events_listener:
    class: Prokl\FrameworkExtensionBundle\Services\Bitrix\OnEpilogFlushListener
    arguments:
      - '@delayed.event.dispatcher'
    tags:
      - { name: bitrix.events.init, module: main, event: OnEpilog, method: handle, sort: 0 }

  bitrix.cache.engine:
    class: Bitrix\Main\Data\ICacheEngine
    factory: ['Bitrix\Main\Data\Cache', 'createCacheEngine']

  Bitrix\Main\Data\Cache:
    arguments: ['@bitrix.cache.engine']

  # Простой PSR-16 кэшер.
  bitrix.simple.cacher:
    class: Prokl\FrameworkExtensionBundle\Services\Bitrix\Psr16Cache\BitrixCacher
    arguments: ['@Bitrix\Main\Data\Cache']
