services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\FrameworkExtensionBundle\Services\Command\Runner:
    class: Prokl\FrameworkExtensionBundle\Services\Command\Runner
    arguments: ['@Symfony\Bundle\FrameworkBundle\Console\Application']
