services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Событие запуска отложенных событий по OnEpilog.
  framework_extension.on_epilog_flush_events_listener:
    class: Prokl\FrameworkExtensionBundle\Services\Bitrix\OnEpilogFlushListener
    arguments:
      - '@delayed.event.dispatcher'
    tags:
      - { name: 'custom.events.init', event: 'shutdown', type: 'add_action', method: 'handle', priority: 0 }
